/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mandelbrot;
import java.util.*;
/**
 *
 * @author Mr. Nobody
 */
class ima{
    double real=0,img=0;    
    public ima(double x,double y){
        this.real=x;
        this.img=y;
    }        
    public ima square(){
        ima sum=new ima(0,0);
        sum.real=this.real*this.real-this.img*this.img;
        sum.img=2*this.real*this.img;
        return sum;
    }
}

public class Mandelbrot extends javax.swing.JFrame {
    /**
     * Creates new form Mandelbrot
     */
    int k=10;
    List<Double> realval=new ArrayList<>(); 
    List<Double> imgval=new ArrayList<>(); 
    int midY,midX,xc,yc;
    
    public Mandelbrot() {
        initComponents();
    }

    private ima iteration(ima a,ima x,int n){
        if(realval.contains(a.real)&&imgval.get(realval.indexOf(a.real))==a.img){ 
            realval.clear();
            imgval.clear();
            return new ima(n,0);            
        }else if(n<k){
            realval.add(a.real);
            imgval.add(a.img);
            n++;
            return iteration(sum(a.square(),x),x,n);           
        }      
        realval.clear();
        imgval.clear();        
        return new ima(-1,0);
    }
    
    public ima sum(ima x,ima y){
        ima sum=new ima(0,0);
        sum.real=x.real+y.real;
        sum.img=x.img+y.img;
        return sum;
    }
    
    public void draw(){
        int aTempFrom=Math.abs(Integer.parseInt(aFrom.getText()));
        int aTempTo=Math.abs(Integer.parseInt(aTo.getText()));
        int bTempFrom=Math.abs(Integer.parseInt(bFrom.getText()));
        int bTempTo=Math.abs(Integer.parseInt(bTo.getText()));
        for(int y=yc-pan.getHeight();y<pan.getHeight()-yc;y++){
            for(int x=xc-pan.getWidth();x<pan.getWidth()-xc;x++){                
                System.out.println(iteration(new ima(0,0),new ima((aTempFrom+aTempTo)/pan.getWidth()*x,(bTempFrom+bTempTo)/pan.getWidth()*y),0).real+" "+iteration(new ima(0,0),new ima((aTempFrom+aTempTo)/pan.getWidth()*x,(bTempFrom+bTempTo)/pan.getWidth()*y),0).img);
                //System.out.println(iteration(new ima(0,0),new ima(x,y),0));
            }
        }
        System.out.println("done");
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mandelbrot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mandelbrot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mandelbrot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mandelbrot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Mandelbrot().setVisible(true);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JPanel();
        drawBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aFrom = new javax.swing.JTextField();
        aTo = new javax.swing.JTextField();
        bFrom = new javax.swing.JTextField();
        bTo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 400, -1));

        drawBut.setText("Draw!");
        drawBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButActionPerformed(evt);
            }
        });
        getContentPane().add(drawBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 421, 127, 73));

        jLabel1.setText("From");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        jLabel2.setText("To");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        jLabel3.setText("A");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 10, -1));

        jLabel4.setText("B");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        aFrom.setText("-2");
        aFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aFromActionPerformed(evt);
            }
        });
        getContentPane().add(aFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 30, -1));

        aTo.setText("2");
        aTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aToActionPerformed(evt);
            }
        });
        getContentPane().add(aTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 30, -1));

        bFrom.setText("-1");
        bFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFromActionPerformed(evt);
            }
        });
        getContentPane().add(bFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 30, -1));

        bTo.setText("1");
        bTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToActionPerformed(evt);
            }
        });
        getContentPane().add(bTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aFromActionPerformed

    private void aToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aToActionPerformed

    private void bFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFromActionPerformed

    private void bToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bToActionPerformed

    private void drawButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButActionPerformed
        // TODO add your handling code here:
        drawBut.setVisible(false);
        draw(); 
    }//GEN-LAST:event_drawButActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aFrom;
    private javax.swing.JTextField aTo;
    private javax.swing.JTextField bFrom;
    private javax.swing.JTextField bTo;
    private javax.swing.JButton drawBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pan;
    // End of variables declaration//GEN-END:variables
}
